# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PaidBills' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PaidBills
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'

  target 'PaidBillsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PaidBillsUITests' do
    # Pods for testing
  end

end
